openapi: 3.0.0
info:
  title: Shutterstock API Reference audio images API
  description: The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media. The API enables searching, browsing, licensing, and downloading images, videos, audio tracks, and sound effects. It also supports editorial content, computer vision features, collection management, and OAuth 2.0 authentication.
  version: 1.0.30
  contact:
    name: Shutterstock Developer Support
    url: https://www.shutterstock.com/developers/contact-us
  license:
    name: Shutterstock API Terms
    url: https://www.shutterstock.com/api/terms
servers:
- url: https://api.shutterstock.com
  description: Shutterstock API
tags:
- name: images
paths:
  /v2/images/search:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: searchImages
      summary: Search for images
      description: This endpoint searches for images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT. Free API accounts show results only from a limited library of media, not the full Shutterstock media library. Also, the numb[...]
  /v2/images/search/suggestions:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getImageSuggestions
      summary: Get suggestions for a search term
      description: This endpoint provides autocomplete suggestions for partial search terms.
    post:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: postImageEntities
      summary: Get keywords from text
      description: This endpoint returns up to 10 important keywords from a block of plain text.
  /v2/images/{id}:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getImage
      summary: Get details about images
      description: This endpoint shows information about an image, including a URL to a preview image and the sizes that it is available in.
  /v2/images/categories:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getImageCategories
      summary: List image categories
      description: This endpoint lists the categories (Shutterstock-assigned genres) that images can belong to.
  /v2/images/{id}/similar:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getSimilarImages
      summary: List similar images
      description: This endpoint returns images that are visually similar to an image that you specify.
  /v2/images/licenses:
    post:
      security:
      - customer_accessCode:
        - licenses.create
        - purchases.view
        ldap_accessCode:
        - user.view
      tags:
      - images
      operationId: licenseImages
      summary: License images
      description: This endpoint gets licenses for one or more images. You must specify the image IDs in the body parameter and other details like the format, size, and subscription ID either in the query parameter or with each image ID in the body parameter. Values in the body parameter override values in the query parameters.
    get:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - images
      operationId: getImageLicenseList
      summary: List image licenses
      description: This endpoint lists existing licenses.
  /v2/images/licenses/{id}/downloads:
    post:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - images
      operationId: downloadImage
      summary: Download images
      description: This endpoint redownloads images that you have already received a license for.
  /v2/images/recommendations:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getImageRecommendations
      summary: List recommended images
      description: This endpoint returns images that customers put in the same collection as the specified image IDs.
  /v2/images/collections:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - images
      operationId: createLightbox
      summary: Create image collections
      description: This endpoint creates one or more image collections (lightboxes). To add images to the collections, use `POST /v2/images/collections/{id}/items`.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - images
      operationId: getLightboxList
      summary: List image collections
      description: This endpoint lists your collections of images and their basic attributes.
  /v2/images/collections/{id}:
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - images
      operationId: getLightbox
      summary: Get the details of image collections
      description: This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use `GET /v2/images/collections/{id}/items`.
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - images
      operationId: renameLightbox
      summary: Rename image collections
      description: This endpoint sets a new name for an image collection.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - images
      operationId: deleteLightbox
      summary: Delete image collections
      description: This endpoint deletes an image collection.
  /v2/images/collections/{id}/items:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - images
      operationId: addLightboxItems
      summary: Add images to collections
      description: This endpoint adds one or more images to a collection by image IDs.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - images
      operationId: getLightboxItems
      summary: Get the contents of image collections
      description: This endpoint lists the IDs of images in a collection and the date that each was added.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - images
      operationId: deleteLightboxItems
      summary: Remove images from collections
      description: This endpoint removes one or more images from a collection.
  /v2/images/collections/featured:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getFeaturedLightboxList
      summary: List featured image collections
      description: This endpoint lists featured collections of specific types and a name and cover image for each collection.
  /v2/images/collections/featured/{id}:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getFeaturedLightbox
      summary: Get the details of featured image collections
      description: This endpoint gets more detailed information about a featured collection, including its cover image and timestamps for its creation and most recent update. To get the images, use `GET /v2/images/collections/featured/{id}/items`.
  /v2/images/collections/featured/{id}/items:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getFeaturedLightboxItems
      summary: Get the contents of featured image collections
      description: This endpoint lists the IDs of images in a featured collection and the date that each was added.
  /v2/images/updated:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getUpdatedImages
      summary: List updated images
      description: This endpoint lists images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show images that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.
  /v2/images:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - images
      operationId: getImageList
      summary: List images
      description: This endpoint lists information about one or more images, including the available sizes.
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    customer_accessCode:
      type: oauth2
      x-shutterstock-realm: customer
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.shutterstock.com/oauth/authorize
          tokenUrl: https://api.shutterstock.com/v2/oauth/access_token
          scopes:
            licenses.create: Grant the ability to download and license media on behalf of the user.
            purchases.view: Grant read-only access to a user's purchase history.
            licenses.view: Grant read-only access to a user's licenses.
            collections.edit: Grant the ability to create new collections, edit a collection, and modify the contents of a collection
            collections.view: Grant read-only access to a collection and its contents.
