openapi: 3.0.0
info:
  title: Shutterstock API Reference audio API
  description: The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media. The API enables searching, browsing, licensing, and downloading images, videos, audio tracks, and sound effects. It also supports editorial content, computer vision features, collection management, and OAuth 2.0 authentication.
  version: 1.0.30
  contact:
    name: Shutterstock Developer Support
    url: https://www.shutterstock.com/developers/contact-us
  license:
    name: Shutterstock API Terms
    url: https://www.shutterstock.com/api/terms
servers:
- url: https://api.shutterstock.com
  description: Shutterstock API
tags:
- name: audio
paths:
  /v2/audio/search:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: searchAudio
      summary: Search for tracks
      description: This endpoint searches for tracks. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter.
  /v2/audio/genres:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: getGenres
      summary: List audio genres
      description: This endpoint returns a list of all audio genres.
  /v2/audio/instruments:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: getInstruments
      summary: List audio instruments
      description: This endpoint returns a list of all audio instruments.
  /v2/audio/moods:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: getMoods
      summary: List audio moods
      description: This endpoint returns a list of all audio moods.
  /v2/audio:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: getTrackList
      summary: List audio tracks
      description: This endpoint lists information about one or more audio tracks, including the description and publication date.
  /v2/audio/{id}:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - audio
      operationId: getTrack
      summary: Get details about audio tracks
      description: This endpoint shows information about a track, including its genres, instruments, and other attributes.
  /v2/audio/licenses:
    post:
      security:
      - customer_accessCode:
        - licenses.create
      tags:
      - audio
      operationId: licenseTrack
      summary: License audio tracks
      description: This endpoint gets licenses for one or more tracks.
    get:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - audio
      operationId: getAudioLicenseList
      summary: List audio licenses
      description: This endpoint lists existing licenses. You can filter the results according to the track ID to see if you have an existing license for a specific track.
  /v2/audio/licenses/{id}/downloads:
    post:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - audio
      operationId: downloadTracks
      summary: Download audio tracks
      description: This endpoint redownloads tracks that you have already received a license for.
  /v2/audio/collections:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - audio
      operationId: createSoundbox
      summary: Create audio collections
      description: This endpoint creates one or more collections (soundboxes). To add tracks, use `POST /v2/audio/collections/{id}/items`.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - audio
      operationId: getSoundboxList
      summary: List audio collections
      description: This endpoint lists your collections of audio tracks and their basic attributes.
  /v2/audio/collections/{id}:
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - audio
      operationId: getSoundbox
      summary: Get the details of audio collections
      description: This endpoint gets more detailed information about a collection, including the number of items in it and when it was last updated. To get the tracks in collections, use `GET /v2/audio/collections/{id}/items`.
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - audio
      operationId: renameSoundbox
      summary: Rename audio collections
      description: This endpoint sets a new name for a collection.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - audio
      operationId: deleteSoundbox
      summary: Delete audio collections
      description: This endpoint deletes a collection.
  /v2/audio/collections/{id}/items:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - audio
      operationId: addSoundboxItems
      summary: Add audio tracks to collections
      description: This endpoint adds one or more tracks to a collection by track IDs.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - audio
      operationId: getSoundboxItems
      summary: Get the contents of audio collections
      description: This endpoint lists the IDs of tracks in a collection and the date that each was added.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - audio
      operationId: deleteSoundboxItems
      summary: Remove audio tracks from collections
      description: This endpoint removes one or more tracks from a collection.
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    customer_accessCode:
      type: oauth2
      x-shutterstock-realm: customer
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.shutterstock.com/oauth/authorize
          tokenUrl: https://api.shutterstock.com/v2/oauth/access_token
          scopes:
            licenses.create: Grant the ability to download and license media on behalf of the user.
            purchases.view: Grant read-only access to a user's purchase history.
            licenses.view: Grant read-only access to a user's licenses.
            collections.edit: Grant the ability to create new collections, edit a collection, and modify the contents of a collection
            collections.view: Grant read-only access to a collection and its contents.
