openapi: 3.0.0
info:
  title: Shutterstock API Reference audio videos API
  description: The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media. The API enables searching, browsing, licensing, and downloading images, videos, audio tracks, and sound effects. It also supports editorial content, computer vision features, collection management, and OAuth 2.0 authentication.
  version: 1.0.30
  contact:
    name: Shutterstock Developer Support
    url: https://www.shutterstock.com/developers/contact-us
  license:
    name: Shutterstock API Terms
    url: https://www.shutterstock.com/api/terms
servers:
- url: https://api.shutterstock.com
  description: Shutterstock API
tags:
- name: videos
paths:
  /v2/videos/search:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: searchVideos
      summary: Search for videos
      description: This endpoint searches for videos. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.
  /v2/videos/search/suggestions:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getVideoSuggestions
      summary: Get suggestions for a search term
      description: This endpoint provides autocomplete suggestions for partial search terms.
  /v2/videos:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getVideoList
      summary: List videos
      description: This endpoint lists information about one or more videos, including the aspect ratio and URLs to previews.
  /v2/videos/{id}:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getVideo
      summary: Get details about videos
      description: This endpoint shows information about a video, including URLs to previews and the sizes that it is available in.
  /v2/videos/licenses:
    post:
      security:
      - customer_accessCode:
        - licenses.create
        - purchases.view
      tags:
      - videos
      operationId: licenseVideos
      summary: License videos
      description: This endpoint gets licenses for one or more videos. You must specify the video IDs in the body parameter and the size and subscription ID either in the query parameter or with each video ID in the body parameter. Values in the body parameter override values in the query parameters.
    get:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - videos
      operationId: getVideoLicenseList
      summary: List video licenses
      description: This endpoint lists existing licenses.
  /v2/videos/licenses/{id}/downloads:
    post:
      security:
      - customer_accessCode:
        - licenses.view
      tags:
      - videos
      operationId: downloadVideos
      summary: Download videos
      description: This endpoint redownloads videos that you have already received a license for.
  /v2/videos/collections:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - videos
      operationId: createClipbox
      summary: Create video collections
      description: This endpoint creates one or more collections (clipboxes). To add videos to collections, use `POST /v2/videos/collections/{id}/items`.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - videos
      operationId: getClipboxList
      summary: List video collections
      description: This endpoint lists your collections of videos and their basic attributes.
  /v2/videos/collections/{id}:
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - videos
      operationId: getClipbox
      summary: Get the details of video collections
      description: This endpoint gets more detailed information about a collection, including the timestamp for its creation and the number of videos in it. To get the videos in collections, use GET /v2/videos/collections/{id}/items.
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - videos
      operationId: renameClipbox
      summary: Rename video collections
      description: This endpoint sets a new name for a collection.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - videos
      operationId: deleteClipbox
      summary: Delete video collections
      description: This endpoint deletes a collection.
  /v2/videos/categories:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getVideoCategories
      summary: List video categories
      description: This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.
  /v2/videos/collections/{id}/items:
    post:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - videos
      operationId: addClipboxItems
      summary: Add videos to collections
      description: This endpoint adds one or more videos to a collection by video IDs.
    get:
      security:
      - customer_accessCode:
        - collections.view
      tags:
      - videos
      operationId: getClipboxItems
      summary: Get the contents of video collections
      description: This endpoint lists the IDs of videos in a collection and the date that each was added.
    delete:
      security:
      - customer_accessCode:
        - collections.edit
      tags:
      - videos
      operationId: deleteClipboxItems
      summary: Remove videos from collections
      description: This endpoint removes one or more videos from a collection.
  /v2/videos/{id}/similar:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getSimilarVideos
      summary: List similar videos
      description: This endpoint searches for videos that are similar to a video that you specify.
  /v2/videos/updated:
    get:
      security:
      - basic: []
      - customer_accessCode: []
      tags:
      - videos
      operationId: getUpdatedVideos
      summary: List updated videos
      description: This endpoint lists videos that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show videos that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    customer_accessCode:
      type: oauth2
      x-shutterstock-realm: customer
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.shutterstock.com/oauth/authorize
          tokenUrl: https://api.shutterstock.com/v2/oauth/access_token
          scopes:
            licenses.create: Grant the ability to download and license media on behalf of the user.
            purchases.view: Grant read-only access to a user's purchase history.
            licenses.view: Grant read-only access to a user's licenses.
            collections.edit: Grant the ability to create new collections, edit a collection, and modify the contents of a collection
            collections.view: Grant read-only access to a collection and its contents.
